version: "3.8"

services:
  db:
    image: mysql:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - $DB_PORT:3306